### ISSUE TITLE
No ability to run composer on a sub-folder of the current Action runner

### ISSUE THREAD

**Issue by lilithebowman** [php-actions/example-composer#7]
path is an invalid variable

I need to be able to specify a sub-folder instead of the main one.

I'm building a vdiff CI Action and it uses 2 different folders for 2 states of the site.

**Comment by g105b** [comment]
Please see here: https://github.com/php-actions/example-composer/runs/1320277543?check_suite_focus=true

Example yml here: https://github.com/php-actions/example-composer/blob/7-subfolder/.github/workflows/subfolder.yaml

Working tree showing subfolder of another composer.json: https://github.com/php-actions/example-composer/tree/7-subfolder

The `working_dir` input is used to change directories. Please re-open this issue if you have further questions.

**Comment by lilithebowman** [comment]
Thanks! Yeah I figured that out eventually.
